djangopro/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('testapp/', include('testapp.urls')),
    path('plotlyapp/', include('plotlyapp.urls')),
]

djangopro/plotlyapp/urls.py
from django.urls import path

from . import views

app_name = 'plotly'

urlpatterns = [
	path('',views.index, name='index'),
]

djangopro/testapp/urls.py
from django.urls import path

from . import views

app_name = 'testapp'
#urlpatterns = [
#    path('login/', views.login, name='login'),
#    path('logout/', views.logout, name='logout'),
#    path('register/', views.register, name='register'),
#]


urlpatterns = [
	path('post/<int:pk>/',views.post_detail, name='post_detail'),
	path('',views.index, name='index'),
]

djangopro/plotlyapp/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.



class Plotly(models.Model):
	data1 = models.FloatField(verbose_name='data1')
	data2 = models.FloatField(verbose_name='data2')
	year = models.IntegerField(verbose_name='year')
	prefecture = models.CharField(max_length=20,verbose_name='prefecture')
	area = models.CharField(max_length=20,verbose_name='area',null=True)
	pop = models.IntegerField(verbose_name='pop')

		

djangopro/testapp/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.conf import settings

# Create your models here.


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text
	
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
	
class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)
	
	def publish(self):
		self.published_date = timezone.now()
		self.save()
	
	def __str__(self):
		return self.title

djangopro/plotlyapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone

from django.shortcuts import render

import os

# Create your views here.

def index(request):
	TMP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
	f = open(os.path.join(TMP_DIR,'templates/plotlyapp','test.txt'), 'w')
	string = 'python output string'
	f.write(string)
	f.close()

#	return HttpResponse("Hello, plotly.")
	return render(request,'plotlyapp/data.html',{})
	

djangopro/testapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from .models import Post

# Create your views here.

def index(request):
#	return HttpResponse("Hello, world. Your're at the polls index.")
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
	return render(request,'testapp/post_list.html',{'posts':posts})


def post_detail(request, pk):
	post = get_object_or_404(Post,pk=pk)
	return render(request,'testapp/post_detail.html',{'post':post})

djangopro/templates/plotlyapp/base.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/plotlyapp.css' %}">
<title>
統計
</title>
</head>
<body>
	<div class="page-header">
		<h1><a href="/">統計</a></h1>
	</div>

	<div class="content container">

		{% block content %}
		{% endblock %}
	</div>


</body>
</html>

djangopro/templates/plotlyapp/data.html
{% extends 'plotlyapp/base.html' %}
{% block content %}
	<div class="post">
		test
	</div>
{% endblock%}

djangopro/templates/testapp/base.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="{% static 'css/testapp.css' %}">
<title>
統計
</title>
</head>
<body>
	<div class="page-header">
		<h1><a href="/">統計</a></h1>
	</div>

	<div class="content container">
	<div class="row">
	<div class="col-md-8">
		{% block content %}
		{% endblock %}
	</div>
	</div>
	</div>

</body>
</html>

djangopro/templates/testapp/post_detail.html
{% extends 'testapp/base.html' %}
{% block content %}
	<div class="post">
		{% if post.published_date %}
			<div class="date">
				{{ post.published_date}}
			</div>
		{% endif%}
		<h2>{{ post.title }}</h2>
		<p>{{ post.text|linebreaksbr }}</p>
	</div>
{% endblock%}

djangopro/templates/testapp/post_list.html
{% extends 'testapp/base.html' %}
{% block content %}
	{% for post in posts %}
		<div class="post">
			<div class="date">
				{{ post.published_date }}
			</div>
			<h2><a href="{% url 'testapp:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
			<p>{{ post.text|linebreaksbr }}</p>
		</div>
	{% endfor %}
{% endblock %}